# Kalman Filters

---
## 1D Kalman Filter

### Update

In [106]:
def update(mean1, var1, mean2, var2):
    new_mean = (var2*mean1 + var1*mean2)/(var1 + var2)
    new_var = 1 / (1/var1 + 1/var2)
    return [new_mean, new_var]


### Predict

In [107]:
def predict(mean1, var1, mean2, var2):
    new_mean = mean1 + mean2
    new_var = var1 + var2
    return [new_mean, new_var]

### Test

In [108]:
# 测量值
measurements = [5., 6., 7., 9., 10.]

# 运动值
motion = [1., 1., 2., 1., 1.]

# 测量不确定性
measurement_sig = 4.

# 运动不确定性
motion_sig = 2.

mu = 0.
sig = 100000

for i in range(len(measurements)):
    [mu, sig] = update(mu, sig, measurements[i], measurement_sig)
    print('update:  ',   [mu, sig])
    [mu, sig] = predict(mu, sig, motion[i], motion_sig)
    print('predict: ', [mu, sig])

update:   [4.99980000799968, 3.9998400063997437]
predict:  [5.99980000799968, 5.999840006399744]
update:   [5.9999200019199534, 2.3999744006143855]
predict:  [6.9999200019199534, 4.3999744006143855]
update:   [6.999961905560072, 2.095232290371059]
predict:  [8.999961905560072, 4.095232290371059]
update:   [8.999981176851481, 2.0235279944923468]
predict:  [9.999981176851481, 4.023527994492347]
update:   [9.999990616024007, 2.005864750396209]
predict:  [10.999990616024007, 4.005864750396209]


---
## 2D Kalman Filter

In [109]:
import numpy as np
measurements = [1., 2., 3.]
x = np.array([[0.], [0.]]) # initial state (location adn velocity)
P = np.array([[1000., 0.], [0., 1000.]]) # initial uncertainty
u = np.array([[0.], [0.]]) # external motion
F = np.array([[1., 1.], [0., 1.]]) # next state function
H = np.array([[1., 0.]]) # mearsurement function
R = np.array([[1.]])  # mearsurement uncertainty
I = np.array([[1., 0.], [0., 1.]]) # identity matrix


In [110]:
for i in range(len(measurements)):
    # mearurement upadte
    Z = np.array([[measurements[i]]])
    y = Z - H.dot(x)
    S = H.dot(P.dot(H.transpose())) + R
    K = P.dot(H.transpose()).dot(np.linalg.inv(S))
    x = x + (K.dot(y))
    
    P = (I - K.dot(H)) * P

    # predict
    x = (F.dot(x)) + u
    P = F.dot(P).dot(F.transpose())

    print(x)
    print(P)
    print("----------------------------------------")



[[0.999001]
 [0.      ]]
[[1000.999001 1000.      ]
 [1000.       1000.      ]]
----------------------------------------
[[2.99800299]
 [0.999002  ]]
[[   2.99401496 1000.        ]
 [   1.99501297 1000.        ]]
----------------------------------------
[[3.9994995]
 [0.9999995]]
[[ 999.75311515 1000.        ]
 [ 999.00348978 1000.        ]]
----------------------------------------
